---
- name: Deploy directus
  become: true
  hosts: all
  remote_user: fedora
  gather_facts: false
  # gather_facts: true

  vars:
    docker_install_compose_plugin: true
    docker_compose_package_state: latest
    project_dir: /opt/directus
    role_map_extension: directus-extension-oidc-role-map

  pre_tasks:
    - name: Wait until the node answers on SSH
      ansible.builtin.wait_for_connection:
        delay: 5                # wait 5 s before the first probe
        timeout: 30            # give it up to 30 s
                                # (module automatically retries)  [oai_citation:0‡docs.ansible.com](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_connection_module.html?utm_source=chatgpt.com)
    - name: Gather facts manually
      ansible.builtin.setup: 
  roles:
    - role: geerlingguy.docker
    - darkwizard242.lazydocker

  tasks:
    # - name: Allow docker user to access tailscaled unix socket
    #   template:
    #     dest: /etc/default/tailscaled
    #     # instead of `src: …` we use `content:`:
    #     content: |
    #       TS_PERMIT_CERT_UID=caddy

    - name: Ensure dir exists
      notify: "Restart compose"
      file:
        path: "{{ project_dir }}/uploads"
        state: directory
        mode: '0777'

    - name: Instantiate Caddyfile
      notify: "Restart compose"
      template:
        src: directus/Caddyfile.j2
        dest: "{{ project_dir }}/Caddyfile"
        force: true

    - name: Ensure dir exists
      notify: "Restart compose"
      file:
        path: "{{ project_dir }}/extensions/{{ role_map_extension }}"
        state: directory
        mode: '0777'
    
    - name: Copy extension
      notify: "Restart compose"
      copy:
        src: directus/extensions/{{ role_map_extension }}/dist/      # Local path (relative to playbook or role)
        dest: "{{ project_dir }}/extensions/{{ role_map_extension }}/dist"  # Destination on remote host
        owner: root
        group: root
        mode: '0777'

    - name: Copy extension
      notify: "Restart compose"
      copy:
        src: directus/extensions/{{ role_map_extension }}/src/      # Local path (relative to playbook or role)
        dest: "{{ project_dir }}/extensions/{{ role_map_extension }}/src"  # Destination on remote host
        owner: root
        group: root
        mode: '0777'

    - name: Copy extension
      notify: "Restart compose"
      copy:
        src: directus/extensions/{{ role_map_extension }}/package.json      # Local path (relative to playbook or role)
        dest: "{{ project_dir }}/extensions/{{ role_map_extension }}/"  # Destination on remote host
        owner: root
        group: root
        mode: '0777'

    - name: Instantiate .env
      notify: "Restart compose"
      template:
        src: directus/dotenv.j2
        dest: "{{ project_dir }}/.env"
        force: true

    - name: Instantiate Caddyfile
      notify: "Restart compose"
      template:
        src: directus/Caddyfile.j2
        dest: "{{ project_dir }}/Caddyfile"
        force: true

    - name: Copy docker-compose.yml
      notify: "Restart compose"
      copy:
        src: directus/docker-compose.yml      # Local path (relative to playbook or role)
        dest: "{{ project_dir }}/docker-compose.yml"  # Destination on remote host
        owner: root
        group: root
        mode: '0644'
       
  handlers:
    - name: "Restart compose"
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        state: present 
        recreate: always
        pull: always

